name: VCMI - vcpkg XP dependencies

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 0' # every Sunday 03:00

jobs:
  build-xp:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: msvc-x64-xp
            triplet: x64-windows-xp
            runner: windows-latest
          - platform: msvc-x86-xp
            triplet: x86-windows-xp
            runner: windows-latest

    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash

    steps:
      # Checkout vcpkg at last commit with XP-friendly ports
      - name: Checkout vcpkg (XP-compatible)
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/vcpkg'
          ref: 2021.05.12

      # Create XP triplets with v141_xp toolset and XP defines
      - name: Create XP triplets
        run: |
          cat <<EOF > triplets/x64-windows-xp.cmake
          set(VCPKG_TARGET_ARCHITECTURE x64)
          set(VCPKG_CRT_LINKAGE dynamic)
          set(VCPKG_LIBRARY_LINKAGE dynamic)
          set(VCPKG_PLATFORM_TOOLSET v141_xp)
          set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          EOF

          cat <<EOF > triplets/x86-windows-xp.cmake
          set(VCPKG_TARGET_ARCHITECTURE x86)
          set(VCPKG_CRT_LINKAGE dynamic)
          set(VCPKG_LIBRARY_LINKAGE dynamic)
          set(VCPKG_PLATFORM_TOOLSET v141_xp)
          set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          EOF

      # Prepare Boost overlay (Boost 1.72 - last XP-compatible)
      - name: Prepare Boost overlay
        run: |
          mkdir -p vcmi-overlay
          git clone https://github.com/microsoft/vcpkg.git temp-vcpkg
          cd temp-vcpkg
          git checkout 2020.01
          cp -r ports/boost* ../vcmi-overlay/
          cd ..
          rm -rf temp-vcpkg

      # Prepare Qt5 overlay (Qt 5.6.3 - last XP-compatible)
      - name: Prepare Qt5 overlay
        run: |
          git clone https://github.com/microsoft/vcpkg.git temp-vcpkg-qt
          cd temp-vcpkg-qt
          git checkout 2020.01
          cp -r ports/qt5* ../vcmi-overlay/
          cd ..
          rm -rf temp-vcpkg-qt

      # Cache vcpkg build artifacts
      - name: Cache vcpkg XP
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/installed
            ${{ github.workspace }}/buildtrees
            ${{ github.workspace }}/downloads
          key: vcpkg-xp-${{ matrix.triplet }}

      - name: Initialize vcpkg
        run: ./bootstrap-vcpkg.bat

      # Install XP-compatible dependencies using overlays
      - name: Install XP dependencies
        run: |
          ./vcpkg.exe install yasm --triplet "${{ matrix.triplet }}" --overlay-ports=vcmi-overlay
          ./vcpkg.exe install \
            tbb fuzzylite sdl2 sdl2-image sdl2-ttf sdl2-mixer[core,mpg123] \
            qt5-base qt5-tools \
            ffmpeg[core,avcodec,avformat,swresample,swscale] \
            boost-filesystem boost-system boost-thread boost-program-options boost-locale \
            boost-iostreams boost-headers boost-foreach boost-format boost-crc boost-logic \
            boost-multi-array boost-ptr-container boost-heap boost-bimap boost-asio \
            boost-stacktrace boost-assign boost-geometry boost-uuid boost-process \
            --triplet "${{ matrix.triplet }}" \
            --overlay-ports=vcmi-overlay

      - name: Export XP packages
        run: |
          ./vcpkg.exe export \
            tbb fuzzylite sdl2 sdl2-image sdl2-ttf sdl2-mixer qt5-base qt5-tools ffmpeg \
            boost-filesystem boost-system boost-thread boost-program-options boost-locale \
            boost-iostreams boost-headers boost-foreach boost-format boost-crc boost-logic \
            boost-multi-array boost-ptr-container boost-heap boost-bimap boost-asio \
            boost-stacktrace boost-assign boost-geometry boost-uuid boost-process \
            --raw --triplet "${{ matrix.triplet }}" \
            --overlay-ports=vcmi-overlay \
            --output=result/vcpkg

      - name: Create XP archive
        run: |
          tar --create --xz --file dependencies-${{ matrix.platform }}.txz -C result vcpkg

      - name: Upload XP artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-${{ matrix.platform }}
          path: ${{ github.workspace }}/dependencies-${{ matrix.platform }}.txz
          compression-level: 0
