name: VCMI - vcpkg XP prepare

on:
  workflow_dispatch:

jobs:
  prepare-xp:
    runs-on: windows-latest

    steps:
      - name: Checkout vcpkg baseline
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: 7aebb481085de7387f8a9975652c26f9053f66df  # 2021.05.12 commit

      - name: Install Visual Studio 2019 Build Tools
        shell: powershell
        run: |
          choco install visualstudio2019buildtools --package-parameters "--quiet --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.v141.x86.x64" -y

      - name: Create XP triplets
        shell: bash
        run: |
          mkdir -p triplets
          cat <<EOF > triplets/x64-windows-xp.cmake
          set(VCPKG_TARGET_ARCHITECTURE x64)
          set(VCPKG_CRT_LINKAGE dynamic)
          set(VCPKG_LIBRARY_LINKAGE dynamic)
          set(VCPKG_PLATFORM_TOOLSET v141_xp)
          set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          EOF

          cat <<EOF > triplets/x86-windows-xp.cmake
          set(VCPKG_TARGET_ARCHITECTURE x86)
          set(VCPKG_CRT_LINKAGE dynamic)
          set(VCPKG_LIBRARY_LINKAGE dynamic)
          set(VCPKG_PLATFORM_TOOLSET v141_xp)
          set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0501 -DWINVER=0x0501")
          EOF

      - name: Prepare Boost overlay (Boost 1.72)
        shell: bash
        run: |
          mkdir -p vcmi-overlay
          git clone https://github.com/microsoft/vcpkg.git temp-vcpkg
          cd temp-vcpkg
          git checkout 7aebb481085de7387f8a9975652c26f9053f66df
          cp -r ports/boost* ../vcmi-overlay/
          cd ..
          rm -rf temp-vcpkg

      - name: Save package list
        shell: bash
        run: |
          cat <<EOF > package-list.txt
          yasm
          tbb
          fuzzylite
          sdl2
          sdl2-image
          sdl2-ttf
          sdl2-mixer[core,mpg123]
          qt5-base
          qt5-tools
          ffmpeg[core,avcodec,avformat,swresample,swscale]
          boost-filesystem
          boost-system
          boost-thread
          boost-program-options
          boost-locale
          boost-iostreams
          boost-headers
          boost-foreach
          boost-format
          boost-crc
          boost-logic
          boost-multi-array
          boost-ptr-container
          boost-heap
          boost-bimap
          boost-asio
          boost-stacktrace
          boost-assign
          boost-geometry
          boost-uuid
          boost-process
          EOF

      - name: Build vcpkg.exe for correct commit
        shell: cmd
        run: |
          set VCPKG_ROOT=%CD%
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          call bootstrap-vcpkg.bat -disableMetrics

      - name: Generate local build script
        shell: bash
        run: |
          cat <<'BAT' > build-xp.cmd
          @echo off
          setlocal
          set SCRIPT_DIR=%~dp0
          cd /d %SCRIPT_DIR%
          set VCPKG_ROOT=%SCRIPT_DIR%

          echo.
          echo === VCMI Windows XP Dependencies Build ===
          echo.

          set VCPKG=%SCRIPT_DIR%vcpkg.exe

          if not exist "%VCPKG%" (
              echo ERROR: vcpkg.exe is missing. This package is broken.
              pause
              exit /b 1
          )

          set VSPATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat"
          if not exist %VSPATH% (
              echo ERROR: vcvarsall.bat not found at %VSPATH%
              pause
              exit /b 1
          )

          call %VSPATH% x64

          echo Building x64 XP packages...
          "%VCPKG%" install @package-list.txt --triplet x64-windows-xp --overlay-ports=vcmi-overlay
          "%VCPKG%" export @package-list.txt --raw --triplet x64-windows-xp --overlay-ports=vcmi-overlay --output=result/x64

          echo Building x86 XP packages...
          "%VCPKG%" install @package-list.txt --triplet x86-windows-xp --overlay-ports=vcmi-overlay
          "%VCPKG%" export @package-list.txt --raw --triplet x86-windows-xp --overlay-ports=vcmi-overlay --output=result/x86

          echo.
          echo === Build complete. Packages exported to result/ ===
          pause
          endlocal
          BAT

      - name: Package prepared vcpkg
        shell: bash
        run: |
          tar --create --xz --file vcpkg-xp.txz \
            triplets vcmi-overlay package-list.txt build-xp.cmd scripts ports bootstrap-vcpkg.bat toolsrc vcpkg.exe

      - name: Upload prepared vcpkg
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-xp
          path: vcpkg-xp.txz
          compression-level: 0
